app:
  jwtExpirationMs: 84600000
  jwtSecret: SecretKey
server:
  error:
    include-binding-errors: always
    include-message: always
  port: 5000
spring:
  datasource:
    password: 54321
    url: jdbc:postgresql://localhost:5432/mady
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
springdoc:
  swagger-ui:
    path: /swagger

aws:
  access_key_id: AKIAY27HEBJN3DT2S55J
  secret_access_key: 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
  bucket:
    region: eu-central-1
    name: mady-s3
    path: https://mady-s3.s3.eu-central-1.amazonaws.com/


