app:
  jwtExpirationMs: 84600000
  jwtSecret: SecretKey
server:
  error:
    include-binding-errors: always
    include-message: always
  port: 5000
spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://mady.cuulkq7yoqaw.eu-central-1.rds.amazonaws.com:5432/first_test_db
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger

AWS:
  bucketname: kutu-erlan-aza
  URL: https://company-kutu-erlan-aza.s3.eu-central-1.amazonaws.com/z